version: '2.1'
services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    volumes:
      - nginx-proxy-certs:/etc/nginx/certs:ro
      - nginx-proxy-vhost:/etc/nginx/vhost.d
      - /opt/docker-files/nginx-proxy/network_internal.conf:/etc/nginx/network_internal.conf
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
      - 443:443
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    networks:
      cloud-network:

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - nginx-proxy-certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy
    networks:
      cloud-network:

  ncdb:
    image: mariadb:10.5.4
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=db_root_passwd      # change this
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=ncuser
      - MYSQL_PASSWORD=db_passwd                # change this
    volumes:
      - ncdb-data:/var/lib/mysql
    networks:
      cloud-network:

  wpdb:
    image: mariadb:10.5.4
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=db_root_passwd      # change this
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wpuser
      - MYSQL_PASSWORD=db_passwd                # change this
    volumes:
      - wpdb-data:/var/lib/mysql
    networks:
      cloud-network:
  
  wp:
    depends_on:
      - wpdb
    image: wordpress:latest
    volumes:
      - wp-data:/var/www/html
    ports:
      - "8080:80"
    restart: always
    environment:
      - WORDPRESS_DB_HOST=wpdb:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
      - VIRTUAL_HOST=your-domain.tld            # change this
      - VIRTUAL_PORT=80
      - VIRTUAL_PROTO=http
      - LETSENCRYPT_HOST=your-domain.tld        # change this
      - LETSENCRYPT_EMAIL=your@email.tld        # change this
      - RESOLVE_TO_PROXY_IP=true
    networks:
      cloud-network:
        
  nc:
    image: nextcloud:stable-apache
    restart: always
    depends_on:
      - ncdb
    volumes:
      - nc-nextcloud:/var/www/html
      - nc-apps:/var/www/html/custom_apps
      - nc-config:/var/www/html/config
      - nc-data:/var/www/html/data
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=ncuser
      - MYSQL_PASSWORD=db_passwd                # change this
      - MYSQL_HOST=ncdb
      - VIRTUAL_HOST=cloud.your-domain.tld      # change this
      - VIRTUAL_PORT=80
      - VIRTUAL_PROTO=http
      - LETSENCRYPT_HOST=cloud.your-domain.tld  # change this
      - LETSENCRYPT_EMAIL=your@email.tld        # change this
      - RESOLVE_TO_PROXY_IP=true
    networks:
      cloud-network:

  collabora:
    image: collabora/code:latest
    restart: always
    environment:
      - "domain=cloud\\.your-domain\\.tld"      # change this (double Backslashes are important here)
      - "username=admin"
      - "password="
      - "SLEEPFORDEBUGGER=0"
      - VIRTUAL_HOST=office.your-domain.tld     # change this
      - VIRTUAL_PORT=9980
      - VIRTUAL_PROTO=https
      - LETSENCRYPT_HOST=office.your-domain.tld # change this
      - LETSENCRYPT_EMAIL=your@email.tld        # change this
      - RESOLVE_TO_PROXY_IP=true
      - NETWORK_ACCESS=internal
    expose:
      - 9980
    cap_add:
      - MKNOD
    networks:
      cloud-network:

networks:
  cloud-network:
    driver: bridge

volumes:
  nginx-proxy-certs:
  nginx-proxy-vhost:
  ncdb-data:
  wpdb-data:
  wp-data:
  nc-nextcloud:
  nc-apps:
  nc-config:
  nc-data:
